FROM nginx:alpine

WORKDIR /app

COPY . .

RUN mkdir -p /app/www

# копируем готовый dist
COPY --from=builder /app/dist /app/www

# nginx конфиг
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]