# HTTP: нужен и для обычного трафика (пока без редиректа), и для acme-challenge
server {
    listen 80;
    server_name bolahnov.ru www.bolahnov.ru;

    root /app/www;
    index index.html index.htm;

    # Путь для проверки Let’s Encrypt (certbot --webroot)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}

# HTTPS: будет работать после выпуска сертификата
server {
    listen 443 ssl;
    server_name bolahnov.ru www.bolahnov.ru;

    ssl_certificate     /etc/letsencrypt/live/bolahnov.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/bolahnov.ru/privkey.pem;

    root /app/www;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }
}